apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  annotations:
    helm.sh/hook: post-install,post-upgrade  # Le hook pour exécuter après l'installation
spec:
  description: "Project contenant les outils CPiN du cluster"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
    {{- range .Values.projects.sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  destinations:
    {{- range .Values.projects.destinations }}
    - namespace: {{ .namespace | quote }}
      server: {{ .server | quote }}
    {{- end }}
---