imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
cert-manager:
  crds:
    enabled: true

clusterIssuers:
  - name: letsencrypt-staging
    email: "your-email@numerique-interieur.com"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx

  - name: letsencrypt-prod
    email: "your-email@numerique-interieur.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
