cpinRepoUrl: &cpinRepoUrl "https://github.com/cloud-pi-native/cpin-external-cluster.git"

sourceRepos:
  - *cpinRepoUrl

# -- URL du dépôt où la Console DSO spécifie les applications à déployer par ArgoCD
dsoZoneRepo: https://gitlab.com/infra/zone.git

cpin:
  apps:
    - name: "cert-manager"
      namespace: "certmanager-cpin"
      valuefile: "./values-cpin.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}
    - name: "kyverno"
      namespace: "kyverno-cpin"
      valuefile: "./values-cpin.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}
    - name: "kyverno-rules"
      namespace: "kyverno-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}
    - name: "falco"
      namespace: "falco-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}
    - name: "minio-operator"
      namespace: "minio-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}
    - name: "cnpg-operator"
      namespace: "cnpg-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: *cpinRepoUrl
      parameters: {}




