apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpin-appsets
  namespace: argo-cpin
spec:
  destination:
    namespace: argo-cpin
    server: https://kubernetes.default.svc
  project: infrastructure
  sources:
  - helm:
      valueFiles:
      - ./values.yaml
      - $argocdValues/argocd-values.yaml
      values: |
        dsoZoneRepo: {{ .Values.dsoZoneRepo }}
        cpinRepo:
          url: {{ .Values.cpinRepo.url }}
          revision: {{ .Values.cpinRepo.revision }}
        appValues: 
{{ .Values.appValues | toYaml | indent 10 }}
    path: applicationSets
    repoURL: {{ .Values.cpinRepo.url }}
    targetRevision: {{ .Values.cpinRepo.revision }}
  - repoURL: {{ .Values.dsoZoneRepo }}
    targetRevision: HEAD
    ref: argocdValues
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
