apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpin-appsets
  namespace: argo-cpin
spec:
  destination:
    namespace: argo-cpin
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    helm:
      valueFiles:
      - ./values.yaml
      values: |
        dsoZoneRepo: {{ .Values.dsoZoneRepo }}
        cpinRepo:
          url: {{ .Values.cpinRepo.url }}
          revision: {{ .Values.cpinRepo.revision }}
    path: applicationSets
    repoURL: {{ .Values.cpinRepo.url }}
    targetRevision: {{ .Values.cpinRepo.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
