apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  annotations:
    helm.sh/hook: post-install,post-upgrade  # Le hook pour exécuter après l'installation
spec:
  description: "Project contenant les outils CPiN du cluster"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
    - "https://github.com/cloud-pi-native/cpin-external-cluster.git"
    - {{ .Values.dsoZoneRepo }}
  destinations:
    - namespace: "argo-cpin"
      server: "https://kubernetes.default.svc"
