{{- range $app := .Values.cpin.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: argo-cpin
  annotations:
    argocd.argoproj.io/sync-wave: "4" # Force la suppression avant le AppProject
spec:
  destination:
    namespace: {{ $app.namespace }}
    server: https://kubernetes.default.svc
  project: app-of-apps-project
  source:
    helm:
      valueFiles:
      - {{ $app.valuefile }}
    path: charts-socle/{{ $app.name }}
    repoURL: {{ $.Values.cpinRepoUrl }}
    targetRevision: {{ $app.branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
{{- end }}
