cpinRepo:
  # -- URL du dépôt où trouver les outils à installer dans le cluster
  url: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
  # -- Branche ou tag du dépôt à utiliser pour installer les outils
  revision: main
## Globally shared configuration
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.demo-cpin.numerique-interieur.com

# -- Values passées aux applications CPIN générées par cpin-appset
appValues: {}

argo-cd:
  crds:
    install: false
  server:
    insecure: true
    service:
      type: ClusterIP  # Utilisation de ClusterIP pour le service ArgoCD server
    certificate:
      # -- Deploy a Certificate resource (requires cert-manager)
      enabled: false
      # -- The name of the Secret that will be automatically created and managed by this Certificate resource
      secretName: argocd-server-tls
      # -- Certificate primary domain (commonName)
      domain: argocd.demo-cpin.numerique-interieur.com
      # Certificate issuer
      ## Ref: https://cert-manager.io/docs/concepts/issuer
      issuer:
        # -- Certificate issuer group. Set if using an external issuer. Eg. `cert-manager.io`
        group: "cert-manager.io"
        # -- Certificate issuer kind. Either `Issuer` or `ClusterIssuer`
        kind: "ClusterIssuer"
        # -- Certificate issuer name. Eg. `letsencrypt`
        name: "letsencrypt-staging"

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      ingressClassName: nginx
      hosts:
        - argocd.demo-cpin.numerique-interieur.com
      tls:
        - hosts:
            - argocd.demo-cpin.numerique-interieur.com 
          secretName: argocd-server-tls
      # -- Uses `server.service.servicePortHttps` instead `server.service.servicePortHttp`
      https: false      
    extraArgs:
      - --insecure # Pour accepter des connexions non sécurisées
  configs:
    cm:
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.local.fr/realms/name
        clientID: argocd-client-name
        clientSecret: tobedefined
        requestedScopes: ["openid", "groups"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
