{{- if .Values.registry.replace }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Pod Security Standards (Baseline) 
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be scanned and secured, representing a high degree of risk. Requiring use of known, approved registries helps reduce threat exposure by ensuring image pulls only come from them. This policy validates that container images only originate from the registry `eu.foo.io` or `bar.io`. Use of this policy requires customization to define your allowable registries.
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  background: false
  rules:
  - name: validate-registries
#    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Unknown image registry."
      pattern:
        spec:
          =(ephemeralContainers):
          - image: {{ .Values.registry.allowedImages | quote }}
          =(initContainers):
          - image: {{ .Values.registry.allowedImages | quote }}
          containers:
          - image: {{ .Values.registry.allowedImages | quote }}
    exclude:
      any:
      - resources:
          namespaces:
            {{- range .Values.registry.excludedNamespaces }}
            - "{{ . }}"
            {{- end }}
{{- end }}