apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy-deny
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy, NetworkPolicy
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/severity: low
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      By default, Kubernetes allows communications across all Pods within a cluster. deny by default
spec:
  rules:
  - name: deny-by-default
#    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: deny-default
      namespace: "{{`{{ request.object.metadata.name }}`}}"
      synchronize: false
      data:
        spec:
          podSelector: {}
          ingress: []
    exclude:
      any:
      - resources:
          namespaces:
            {{- range .Values.excludedNamespaces }}
            - "{{ . }}"
            {{- end }}
