apiVersion: v2
name: minio-operator
type: application
version: 6.0.1
appVersion: "v6.0.1"
description: minio operator
dependencies: 
  - name: operator
    alias: minio-operator
    version: 6.0.1
    repository: https://operator.min.io
  - name: tenant
    alias: minio-tenant
    version: 6.0.1
    repository: https://operator.min.io
    condition: minio-tenant.enabled