---
# Generate secret for user and SSE-S3 encryption before deploy
# Update $VAR 
# cat /dev/urandom | head -c 32 | base64 -

# apiVersion: v1
# kind: Secret
# metadata:
#   name: $TENANT-env-configuration
#   namespace: infra-minio-operator
# type: Opaque
# stringData:
#   config.env: |-
#     export MINIO_ROOT_USER=admin
#     export MINIO_ROOT_PASSWORD=$PASSWORD
#     export MINIO_KMS_SECRET_KEY=minio-kms-key:$KEY_GENERATED_BY_RANDOM
#     export MINIO_PROMETHEUS_AUTH_TYPE="public"

minio-tenant:
  enabled: false